// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRf8ePI-waDBCoya7lM0ePw8eFa3QZrlE',
    appId: '1:80781174164:web:e6c82874b0818ab1491b81',
    messagingSenderId: '80781174164',
    projectId: 'schoola-buddy',
    authDomain: 'schoola-buddy.firebaseapp.com',
    storageBucket: 'schoola-buddy.firebasestorage.app',
    measurementId: 'G-ZDS5YRMP6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmh-I3RfxMYYi--P7EFyEyixgrSc2row8',
    appId: '1:80781174164:android:ef94c854a91e0900491b81',
    messagingSenderId: '80781174164',
    projectId: 'schoola-buddy',
    storageBucket: 'schoola-buddy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPua4ryR_ERfRKPOdk-VMREI8Exl4gbok',
    appId: '1:80781174164:ios:acb4458d0eebeec3491b81',
    messagingSenderId: '80781174164',
    projectId: 'schoola-buddy',
    storageBucket: 'schoola-buddy.firebasestorage.app',
    iosClientId: '80781174164-q5tohikocqrl41ihrl8or1uo3d80d4an.apps.googleusercontent.com',
    iosBundleId: 'com.example.schoolaBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPua4ryR_ERfRKPOdk-VMREI8Exl4gbok',
    appId: '1:80781174164:ios:acb4458d0eebeec3491b81',
    messagingSenderId: '80781174164',
    projectId: 'schoola-buddy',
    storageBucket: 'schoola-buddy.firebasestorage.app',
    iosClientId: '80781174164-q5tohikocqrl41ihrl8or1uo3d80d4an.apps.googleusercontent.com',
    iosBundleId: 'com.example.schoolaBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRf8ePI-waDBCoya7lM0ePw8eFa3QZrlE',
    appId: '1:80781174164:web:8c17b5ec3a87c3c0491b81',
    messagingSenderId: '80781174164',
    projectId: 'schoola-buddy',
    authDomain: 'schoola-buddy.firebaseapp.com',
    storageBucket: 'schoola-buddy.firebasestorage.app',
    measurementId: 'G-WQWGMXZTMP',
  );
}
